# Generated by Django 4.0.2 on 2022-12-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklockerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignlocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('lockernumber', models.CharField(blank=True, max_length=100, null=True)),
                ('keynumber', models.CharField(blank=True, max_length=100, null=True)),
                ('instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee', models.CharField(blank=True, max_length=100, null=True)),
                ('relnominee', models.CharField(blank=True, max_length=100, null=True)),
                ('valuable', models.CharField(blank=True, max_length=100, null=True)),
                ('idimage', models.CharField(blank=True, max_length=100, null=True)),
                ('picimage', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
