# Generated by Django 4.1.2 on 2022-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banklockerapp", "0007_alter_assignlocker_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignlocker",
            name="idimage",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="assignlocker",
            name="picimage",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
