# Generated by Django 4.1.2 on 2023-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banklockerapp", "0009_rename_idimage_assignlocker_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignlocker",
            name="status",
            field=models.CharField(
                blank=True, default="Inactive", max_length=200, null=True
            ),
        ),
    ]
